### ISSUE TITLE
Kafka broker not available

### ISSUE THREAD

**Issue by kebab-mai-haddi** [rrbarbosa/debezium-docker#1]
Hi!
I am running debezium from the command given [here](https://github.com/debezium/debezium-examples/tree/master/tutorial#using-mongodb). I want to connect to kafka using my python consumer. Your code uses `kafka` as the bootstrap server, mine is not working on kafka. It only works on `localhost` and does not consume any message(although, it does fetch the topics available but no message, even though messages are available from the console). 

The error that I am facing is:
```
raceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aviralsrivastava/.virtualenvs/iteration_de_streaming_1/lib/python3.7/site-packages/kafka/consumer/group.py", line 353, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/Users/aviralsrivastava/.virtualenvs/iteration_de_streaming_1/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/Users/aviralsrivastava/.virtualenvs/iteration_de_streaming_1/lib/python3.7/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

**Comment by mariomtzjr** [comment]
Hi, I have the same problem: 

I'm following the Debezium's tutorial, but I don't use mysql container because I'm trying to connect me to different database. The connector's status is RUNNING for task and connector, but when I run the watcher, I can't see data. So, I create a python consumer, but I get this:

```
Traceback (most recent call last):
  File "consumer.py", line 7, in <module>
    auto_offset_reset='earliest')
  File "/home/ubuntu/.local/lib/python3.5/site-packages/kafka/consumer/group.py", line 353, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

**Comment by divyeshBhartiya** [comment]
Hi, I'm also facing the same issue.
Please let me know in case anybody has resolved it or found the solution.
